### ISSUE TITLE
New lib, same Quaternion

### ISSUE THREAD

**Issue by KitsuneRal** [flathub/com.github.quaternion#10]
What is the right way to rebuild the Flatpak with the updated version of the library - should I change Quaternion Flatpak's version somehow?

**Comment by TingPing** [comment]
This is a pretty vague question... Just read the manifest and change the updated libs? `flatpak-builder build --force-clean --install-deps-from=flathub com.github.quaternion.json` to test building.

**Comment by Lonsfor** [comment]
change https://github.com/flathub/com.github.quaternion/blob/c079ca3c80f99ac253817779b29b88bcc88bad1e/com.github.quaternion.json#L24 with the new lib version and hash.

and maybe consider changing the `type` from `archive` to `git` so you don't have to check for the new hash every time

**Comment by KitsuneRal** [comment]
Well, my question was fairly specific but - after a more careful look - non-sensical, since there's no such thing as the flatpak package _version_. Thanks everybody.
