### ISSUE TITLE
Unable to run after installation

### ISSUE THREAD

**Issue by jg110** [flathub/com.github.quaternion#13]
On Gentoo I'm unable to run the package after installing.

### Steps to Reproduce

- `flatpak install https://flathub.org/repo/appstream/com.github.quaternion.flatpakref`
- Complete installation
- `flatpak run com.github.quaternion`

### Results

Expected: Quaternion runs as normal

Actual: `bwrap: Can't find source path /var/run/user/1000/doc/by-app/com.github.quaternion: No such file or directory`

I don't have a `by-app` directory within /var/run/user/1000/doc.

**Comment by KitsuneRal** [comment]
Sorry for long silence. This very much seems like something wrong with Flatpak on your machine. Can you try again?

**Comment by KitsuneRal** [comment]
Closing for now - please reopen if it's still happening.
