### ISSUE TITLE
Changing the prefix

### ISSUE THREAD

**Issue by KitsuneRal** [flathub/com.github.quaternion#14]
Is there an established process (and/or known caveats) on migrating an application to a different prefix? I'm considering to use im.quotient.Quaternion instead of com.github.Quaternion (quotient.im will be the home of the entire project including libQMatrixClient, now known as libQuotient, and Quaternion).

**Comment by TingPing** [comment]
A new repo gets made and the old one gets marked end-of-life. In the near future it should automatically install the new one for users also.

Generally the process is just re-submit it against flathub/flathub and it can be handled then.

**Comment by KitsuneRal** [comment]
Thanks. Maybe sometime later then - when the automatic upgrade path is in place.

**Comment by TingPing** [comment]
You can track that here: https://github.com/flathub/buildbot/pull/6
