### ISSUE TITLE
Tray icon falls back to XEmbed

### ISSUE THREAD

**Issue by KitsuneRal** [flathub/com.github.quaternion#15]
See discussion starting from https://matrix.to/#/!yBCfIaIJPwYXMoldTd:matrix.org/%24vwUew-wX5tK3sLdeIffWT-R_LGbIQkWuYrnU2Kn7DdU.

**Comment by TingPing** [comment]
test `flatpak run --talk-name=org.kde.StatusNotifierWatcher com.github.quaternion` and add that permission if it works.

**Comment by KitsuneRal** [comment]
Fixed by https://github.com/flathub/com.github.quaternion/commit/bfde2545e1a60489a165bb5d4507dea6a30d7e6c
