### ISSUE TITLE
Broken icon in GNOME software center

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.github.quaternion#16]
Hi. Icon of this application appearing broken in GNOME software center - see screenshot bellow:

![quaternion-broken-icon](https://user-images.githubusercontent.com/25375330/83351079-89919a80-a330-11ea-9185-1903593663bb.png)

**Comment by KitsuneRal** [comment]
The icon is on its place at flathub.org though. What's your environment - OS version, GNOME version?

**Comment by Nokia808** [comment]
I'm on Fedora Linux X64 bit, Cinnamon edition. Cinnamon DE version 4.4.8 & GNOME software center version 3.36.1

Best.

**Comment by Nokia808** [comment]
Today, I refresh catch in my GNOME software center but issue is still existing ...

**Comment by Steinhagen** [comment]
The icon is missing in flathub.org right now.

**Comment by AsciiWolf** [comment]
Still the same issue.

**Comment by KitsuneRal** [comment]
Fixed in beta channel as of now. The stable channel will be updated in a couple of weeks.
