### ISSUE TITLE
not available on flathub?

### ISSUE THREAD

**Issue by edinosma** [flathub/com.github.quaternion#2]
trying to download the flatpak using the command  `flatpak install --from https://flathub.org/repo/appstream/com.github.quaternion` spits out `Key file contains line “<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">” which is not a key-value pair, group, or comment`.
viewing the link in a browser leads to flathub's 404 page.

**Comment by TingPing** [comment]
Because that is the wrong link.

`flatpak install https://flathub.org/repo/appstream/com.github.quaternion.flatpakref`

**Comment by KitsuneRal** [comment]
Thanks for spotting that - there's an apparent typo in README.md.
