### ISSUE TITLE
Crashes when moving focus from the Matrix-ID field after entering my ID

### ISSUE THREAD

**Issue by ntninja** [flathub/com.github.quaternion#6]
# Steps to reproduce

  1. Enter „@alexander:ninetailed.ninja“ into the Matrix-ID field
  2. Press Tab or click into some other field

# Expected behaviour

Nothing really, but it's nice that it trys to change the server URL automatically when entering a full ID

# Actual behaviour

Quaternion crashes with „ASSERT: "!isEmpty()" in file /usr/include/QtCore/qlist.h, line 345“.

This does not occur with Quaternion built from latest master at https://github.com/QMatrixClient/Quaternion, nor does it happen when entering any Matrix-ID that does not end with `:ninetailed.ninja` for some reason.

**Comment by KitsuneRal** [comment]
Thanks for the report; this seems to be triggered by the buggy server resolution code that was disabled sometime ago (which is the reason why you don't observe it if building from the latest master). Quaternion 0.1 will be released fairly soon; meanwhile, as a possible workaround, I can only recommend entering MXID localpart in User ID and serverpart in Server.
